name: Docker build
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull previous build result (for cache)
      run: docker pull misskey/misskey:latest
    - name: Build docker container
      run: docker build --cache-from misskey/misskey:latest -t misskey/misskey .
